main: ${PACKAGE}.${NAME}
name: ${NAME}
version: "${VERSION}"
api-version: "1.21.1"
author: AUTHOR
description: DESCRIPTION
commands:
  imagine:
    description: Records what a player imagines in the server logs
    usage: "/imagine <text> - Log your imagination to the server"
    permission: imagination.use
permissions:
  imagination.use:
    description: Allows players to use the imagine command
    default: true
